# Neuroharmonize datasets

This is a notebook to apply neuroHarmonize: a ComBat-GAM  non-linear allowing algorithm over our data to create neuroHarmonized datasets. It should be run in the `neurogamy` environment. Here we harmonize cvasl parameters, but also include Intracranial volume . ICV is a derived parameter (5/9/2024)

In [1]:
import os
import sys
from neuroHarmonize import harmonizationLearn
import pandas as pd
import numpy as np

# sys.path.insert(0, '../../') # path to functions

# import cvasl.seperated as sep

In [2]:
EDIS = pd.read_csv('../new_data/TrainingDataComplete_EDIS.csv')
HELIUS = pd.read_csv('../new_data/TrainingDataComplete_HELIUS.csv')
SABRE = pd.read_csv('../new_data/TrainingDataComplete_SABRE.csv')
MRI = pd.read_csv('../new_data/TrainingDataComplete_StrokeMRI.csv')
TOP = pd.read_csv('../new_data/TrainingDataComplete_TOP.csv')
Insight46 = pd.read_csv('../new_data/TrainingDataComplete_Insight46.csv')
#TOP

calculating ICV by existing columns- > we will take GM_ICV ratio = GM vol / ICV
therefore ICV =GM_vol / GM_ICV ratio

# >>>>>>

In [3]:
datasets = [TOP, MRI, SABRE, HELIUS, EDIS, Insight46]
for specific_set in datasets:
    specific_set['ICV'] = specific_set['GM_vol'] / specific_set['GM_ICVRatio']

In [4]:
TOP

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
0,sub-0668_1,287,50.40,1,1,0.64252,0.48470,0.26711,0.46081,0.80843,...,90.5294,80.9975,57.9326,72.1759,1450,2025,PCASL,3DSpiral,Yes,1.394327
1,sub-0532_1,222,37.02,1,1,0.71890,0.59546,0.31236,0.44193,0.80798,...,101.2955,90.3336,67.8547,80.1958,1450,2025,PCASL,3DSpiral,Yes,1.626728
2,sub-0529_1,220,30.57,1,1,0.66610,0.45798,0.28326,0.47330,0.79873,...,108.6481,99.6353,72.4565,87.2374,1450,2025,PCASL,3DSpiral,Yes,1.407353
3,sub-0393_1,168,47.05,1,1,0.65366,0.50449,0.22497,0.47260,0.83735,...,92.8599,81.2144,61.5686,73.7697,1450,2025,PCASL,3DSpiral,Yes,1.383115
4,sub-0593_1,244,44.63,1,1,0.66182,0.48806,0.27842,0.46336,0.80507,...,83.5410,77.6834,67.6360,71.2309,1450,2025,PCASL,3DSpiral,Yes,1.428306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,sub-1053_1,453,33.55,1,1,0.69397,0.49065,0.32276,0.46038,0.78588,...,75.9264,68.4207,55.3558,61.3110,1450,2025,PCASL,3DSpiral,Yes,1.507385
525,sub-1085_1,473,44.43,0,1,0.69453,0.54671,0.38307,0.42758,0.76416,...,72.7612,66.9856,52.4624,60.4133,1450,2025,PCASL,3DSpiral,Yes,1.624328
526,sub-1048_1,449,45.60,1,1,0.60441,0.43197,0.24444,0.47189,0.80915,...,89.2308,73.1897,62.6053,71.1596,1450,2025,PCASL,3DSpiral,Yes,1.280828
527,sub-1100_1,485,46.20,0,1,0.69553,0.54544,0.33771,0.44058,0.78608,...,80.2207,69.8548,54.5726,64.4506,1450,2025,PCASL,3DSpiral,Yes,1.578669
528,sub-0235_1,86,43.46,0,1,0.72478,0.53293,0.41482,0.43334,0.75198,...,83.8033,79.3069,55.6249,67.8070,1450,2025,PCASL,3DSpiral,Yes,1.672543

In [5]:
HELIUS.columns

Index(['participant_id', 'ID', 'Age', 'Sex', 'Site', 'GM_vol', 'WM_vol',
       'CSF_vol', 'GM_ICVRatio', 'GMWM_ICVRatio', 'WMHvol_WMvol', 'WMH_count',
       'DeepWM_B_CoV', 'ACA_B_CoV', 'MCA_B_CoV', 'PCA_B_CoV', 'TotalGM_B_CoV',
       'DeepWM_B_CBF', 'ACA_B_CBF', 'MCA_B_CBF', 'PCA_B_CBF', 'TotalGM_B_CBF',
       'LD', 'PLD', 'Labelling', 'Readout', 'M0', 'ICV'],
      dtype='object')

In [6]:
HELIUS.tail(3)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
553,sub-205033_1,419,61,1,1,0.49507,0.38732,0.38714,0.38996,0.69505,...,86.2320,79.8498,64.5891,72.6402,1800,1800,PCASL,2DEPI,Yes,1.269540
554,sub-101158_1,18,68,0,1,0.63306,0.52261,0.42754,0.39986,0.72995,...,63.7018,57.0480,44.9687,52.4774,1800,1800,PCASL,2DEPI,Yes,1.583204
555,sub-138548_1,260,58,1,1,0.52170,0.43188,0.28295,0.42191,0.77117,...,69.6768,62.2413,48.2963,57.0175,1800,1800,PCASL,2DEPI,Yes,1.236520

In [7]:
TOP['Site'] = 0
MRI['Site'] = 1
MRI.head(3)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
0,sub-5917601_1,160,70.713706,1,1,0.64526,0.44079,0.45182,0.41958,0.70620,...,87.7219,77.3645,61.7552,67.7197,1450,2025,PCASL,3DSpiral,Yes,1.537871
1,sub-5931802_1,395,47.583562,1,1,0.64172,0.49929,0.31811,0.43980,0.78199,...,92.8927,83.1294,68.1315,74.5787,1450,2025,PCASL,3DSpiral,Yes,1.459118
2,sub-5911901_1,58,74.104110,1,1,0.56755,0.48915,0.45260,0.37604,0.70013,...,75.6066,63.4006,60.2426,60.9976,1450,2025,PCASL,3DSpiral,Yes,1.509281

## We found there is one aprticipant from two seperate sights (HELIUS and SABRE) named the same. There fore we will show and switch this

In [8]:
HELIUS[HELIUS['participant_id']=='sub-153852_1']

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
289,sub-153852_1,332,44,1,1,0.67683,0.58467,0.33137,0.42491,0.79197,...,60.0353,49.614,46.1622,48.5433,1800,1800,PCASL,2DEPI,Yes,1.592878

In [9]:
SABRE[SABRE['participant_id']=='sub-153852_1']

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
46,sub-153852_1,196,68,0,1,0.52835,0.37208,0.31019,0.43643,0.74378,...,60.0206,51.7182,46.281,49.9338,1800,2000,PCASL,2DEPI,Yes,1.210618

In [10]:
HELIUS.loc[HELIUS['participant_id']=='sub-153852_1', 'participant_id'] = 'sub-153852_1H'

In [11]:
TOP.head(3)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
0,sub-0668_1,287,50.40,1,0,0.64252,0.48470,0.26711,0.46081,0.80843,...,90.5294,80.9975,57.9326,72.1759,1450,2025,PCASL,3DSpiral,Yes,1.394327
1,sub-0532_1,222,37.02,1,0,0.71890,0.59546,0.31236,0.44193,0.80798,...,101.2955,90.3336,67.8547,80.1958,1450,2025,PCASL,3DSpiral,Yes,1.626728
2,sub-0529_1,220,30.57,1,0,0.66610,0.45798,0.28326,0.47330,0.79873,...,108.6481,99.6353,72.4565,87.2374,1450,2025,PCASL,3DSpiral,Yes,1.407353

# Here we will harmonize just TOP and StrokeMRI

In [12]:
TOPMRI = pd.concat([TOP, MRI])
TOPMRI.head(3)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
0,sub-0668_1,287,50.40,1,0,0.64252,0.48470,0.26711,0.46081,0.80843,...,90.5294,80.9975,57.9326,72.1759,1450,2025,PCASL,3DSpiral,Yes,1.394327
1,sub-0532_1,222,37.02,1,0,0.71890,0.59546,0.31236,0.44193,0.80798,...,101.2955,90.3336,67.8547,80.1958,1450,2025,PCASL,3DSpiral,Yes,1.626728
2,sub-0529_1,220,30.57,1,0,0.66610,0.45798,0.28326,0.47330,0.79873,...,108.6481,99.6353,72.4565,87.2374,1450,2025,PCASL,3DSpiral,Yes,1.407353

In [13]:
TOPMRI.tail(3)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,M0,ICV
575,sub-5931002_1,381,54.769863,0,1,0.66914,0.56129,0.41598,0.40642,0.74734,...,68.9781,58.6687,46.1167,53.3346,1450,2025,PCASL,3DSpiral,Yes,1.646425
576,sub-5925701_1,294,66.639344,1,1,0.58411,0.47607,0.34966,0.41431,0.75199,...,59.8056,58.3224,40.4508,46.3041,1450,2025,PCASL,3DSpiral,Yes,1.409838
577,sub-5934201_1,436,45.336986,1,1,0.62603,0.44826,0.30040,0.45540,0.78148,...,97.4488,84.5106,74.9190,81.1740,1450,2025,PCASL,3DSpiral,Yes,1.374682

In [14]:
TOPMRI.columns

Index(['participant_id', 'ID', 'Age', 'Sex', 'Site', 'GM_vol', 'WM_vol',
       'CSF_vol', 'GM_ICVRatio', 'GMWM_ICVRatio', 'WMHvol_WMvol', 'WMH_count',
       'DeepWM_B_CoV', 'ACA_B_CoV', 'MCA_B_CoV', 'PCA_B_CoV', 'TotalGM_B_CoV',
       'DeepWM_B_CBF', 'ACA_B_CBF', 'MCA_B_CBF', 'PCA_B_CBF', 'TotalGM_B_CBF',
       'LD', 'PLD', 'Labelling', 'Readout', 'M0', 'ICV'],
      dtype='object')

In [15]:
TOPMRI.Labelling.unique()

array(['PCASL'], dtype=object)

In [16]:
TOPMRI.Site.unique()

array([0, 1])

In [17]:
datasets = [TOPMRI, TOP, MRI, SABRE, HELIUS, EDIS, Insight46]


def deal_with_readout_and_labelling(dataframes_list, droppies):
    """
    This function takes a list of asl containing dataframes
    of extracted MRI parameters and converts some of the ASL
    parameters to numerical values so they can be used for
    machine learning.


    :param dataframes_list: list of dataframes
    :type dataframes_list: list
    :param droppies: list of columns to drop
    :type droppies: list


    :returns: list of dataframes transformed
    :rtype: list
    """
    new_frames = []
    for frame in dataframes_list:
        frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
        frame.Readout = frame.Readout.replace(
            to_replace=['3DSpiral', '2DEPI', '3DGRASE'],
            value=[1, 2, 3]
        )
        frame.Labelling = frame.Labelling.replace(
            to_replace=['PCASL', 'PASL'],
            value=[1, 2]
        )
        frame = frame.drop(droppies, axis=1)
        new_frames.append(frame)
    return new_frames

new_frames = deal_with_readout_and_labelling(datasets, ['M0'])

/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Readout = frame.Readout.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Labelling = frame.Labelling.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Readout = frame.Readout.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Labelling = frame.Labelling.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Readout = frame.Readout.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Labelling = frame.Labelling.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Readout = frame.Readout.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Labelling = frame.Labelling.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Readout = frame.Readout.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Labelling = frame.Labelling.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Readout = frame.Readout.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Labelling = frame.Labelling.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.M0 = frame.M0.replace(to_replace=['No', 'Yes'], value=[1, 2])
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Readout = frame.Readout.replace(
/var/folders/nd/48n8vtls37q77z5hpvz8wcjh0000gq/T/ipykernel_76293/3355809464.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frame.Labelling = frame.Labelling.replace(

In [18]:
# check all is in order
#datasets = [TOPMRI, TOP, MRI, SABRE, HELIUS, EDIS, Insight46]
for frame in new_frames:
    print(len(frame))
print(len(TOPMRI))
print(len(TOP))
print(len(MRI))
print(len(SABRE))
print(len(HELIUS))
print(len(EDIS))
print(len(Insight46))

1107
529
578
706
556
346
617
1107
529
578
706
556
346
617

In [19]:
print(MRI.Site.unique())

[1]

In [20]:
for frame in new_frames:
    print(len(frame))
print(len(TOPMRI))
print(len(TOP))
print(len(MRI))
print(len(SABRE))
print(len(HELIUS))
print(len(EDIS))
print(len(Insight46))

1107
529
578
706
556
346
617
1107
529
578
706
556
346
617

In [21]:
#new_frames[0]
TOPMRI = new_frames[0]
TOP = new_frames[1]
MRI = new_frames[2]
SABRE = new_frames[3]
HELIUS = new_frames[4]
EDIS = new_frames[5]
Insight46 = new_frames[6]

In [22]:
TOPMRI.columns= TOPMRI.columns.str.lower()
TOPMRI

,participant_id,id,age,sex,site,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,...,deepwm_b_cbf,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,ld,pld,labelling,readout,icv
0,sub-0668_1,287,50.400000,1,0,0.64252,0.48470,0.26711,0.46081,0.80843,...,24.9902,90.5294,80.9975,57.9326,72.1759,1450,2025,1,1,1.394327
1,sub-0532_1,222,37.020000,1,0,0.71890,0.59546,0.31236,0.44193,0.80798,...,24.2061,101.2955,90.3336,67.8547,80.1958,1450,2025,1,1,1.626728
2,sub-0529_1,220,30.570000,1,0,0.66610,0.45798,0.28326,0.47330,0.79873,...,26.5891,108.6481,99.6353,72.4565,87.2374,1450,2025,1,1,1.407353
3,sub-0393_1,168,47.050000,1,0,0.65366,0.50449,0.22497,0.47260,0.83735,...,27.4124,92.8599,81.2144,61.5686,73.7697,1450,2025,1,1,1.383115
4,sub-0593_1,244,44.630000,1,0,0.66182,0.48806,0.27842,0.46336,0.80507,...,23.9605,83.5410,77.6834,67.6360,71.2309,1450,2025,1,1,1.428306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,sub-5928501_1,342,67.178082,1,1,0.57040,0.44852,0.33133,0.42244,0.75462,...,24.4424,72.0298,60.8287,43.0370,50.3654,1450,2025,1,1,1.350251
574,sub-5910502_1,37,67.794521,1,1,0.56474,0.44446,0.34731,0.41632,0.74397,...,22.2190,69.3495,60.6663,52.6914,54.0085,1450,2025,1,1,1.356505
575,sub-5931002_1,381,54.769863,0,1,0.66914,0.56129,0.41598,0.40642,0.74734,...,24.0877,68.9781,58.6687,46.1167,53.3346,1450,2025,1,1,1.646425
576,sub-5925701_1,294,66.639344,1,1,0.58411,0.47607,0.34966,0.41431,0.75199,...,22.6379,59.8056,58.3224,40.4508,46.3041,1450,2025,1,1,1.409838
577,sub-5934201_1,436,45.336986,1,1,0.62603,0.44826,0.30040,0.45540,0.78148,...,24.8571,97.4488,84.5106,74.9190,81.1740,1450,2025,1,1,1.374682

For neuroharmonize in this case we will not include labelling, readout, ld or pld or m0

# For neuroharmonization we do not use 'ld', 'pld', 'labelling', or 'readout' at all

# Mistake deep white matter included, must delete

In [23]:
unharm_features = [
    'participant_id',
    'gm_vol', 
    'wm_vol',
    'csf_vol', 
    'gm_icvratio', 
    'gmwm_icvratio', 
    'wmhvol_wmvol', 
    'wmh_count',
]
       #'ld', 'pld', 'labelling', 'readout', 'm0']
features_to_harmonize = [
    'aca_b_cov', 
    'mca_b_cov', 
    'pca_b_cov', 
    'totalgm_b_cov',
    'aca_b_cbf', 
    'mca_b_cbf', 
    'pca_b_cbf', 
    'totalgm_b_cbf',
]

In [24]:
TOPMRI

,participant_id,id,age,sex,site,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,...,deepwm_b_cbf,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,ld,pld,labelling,readout,icv
0,sub-0668_1,287,50.400000,1,0,0.64252,0.48470,0.26711,0.46081,0.80843,...,24.9902,90.5294,80.9975,57.9326,72.1759,1450,2025,1,1,1.394327
1,sub-0532_1,222,37.020000,1,0,0.71890,0.59546,0.31236,0.44193,0.80798,...,24.2061,101.2955,90.3336,67.8547,80.1958,1450,2025,1,1,1.626728
2,sub-0529_1,220,30.570000,1,0,0.66610,0.45798,0.28326,0.47330,0.79873,...,26.5891,108.6481,99.6353,72.4565,87.2374,1450,2025,1,1,1.407353
3,sub-0393_1,168,47.050000,1,0,0.65366,0.50449,0.22497,0.47260,0.83735,...,27.4124,92.8599,81.2144,61.5686,73.7697,1450,2025,1,1,1.383115
4,sub-0593_1,244,44.630000,1,0,0.66182,0.48806,0.27842,0.46336,0.80507,...,23.9605,83.5410,77.6834,67.6360,71.2309,1450,2025,1,1,1.428306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,sub-5928501_1,342,67.178082,1,1,0.57040,0.44852,0.33133,0.42244,0.75462,...,24.4424,72.0298,60.8287,43.0370,50.3654,1450,2025,1,1,1.350251
574,sub-5910502_1,37,67.794521,1,1,0.56474,0.44446,0.34731,0.41632,0.74397,...,22.2190,69.3495,60.6663,52.6914,54.0085,1450,2025,1,1,1.356505
575,sub-5931002_1,381,54.769863,0,1,0.66914,0.56129,0.41598,0.40642,0.74734,...,24.0877,68.9781,58.6687,46.1167,53.3346,1450,2025,1,1,1.646425
576,sub-5925701_1,294,66.639344,1,1,0.58411,0.47607,0.34966,0.41431,0.75199,...,22.6379,59.8056,58.3224,40.4508,46.3041,1450,2025,1,1,1.409838
577,sub-5934201_1,436,45.336986,1,1,0.62603,0.44826,0.30040,0.45540,0.78148,...,24.8571,97.4488,84.5106,74.9190,81.1740,1450,2025,1,1,1.374682

# >>>>>>

In [25]:
TOPMRI_semi_features = TOPMRI[unharm_features]
TOPMRI_features = TOPMRI[features_to_harmonize]
TOPMRI_covariates = TOPMRI[['age', 'sex','site', 'icv']]
TOPMRI_covariates = TOPMRI_covariates.rename(columns={'site': 'SITE'})
TOPMRI_covariates.head(3)

     age  sex  SITE       icv
0  50.40    1     0  1.394327
1  37.02    1     0  1.626728
2  30.57    1     0  1.407353

In [26]:
TOPMRI_features

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf
0,0.17747,0.20996,0.24951,0.24191,90.5294,80.9975,57.9326,72.1759
1,0.17620,0.23222,0.21187,0.23518,101.2955,90.3336,67.8547,80.1958
2,0.19233,0.20855,0.19810,0.21863,108.6481,99.6353,72.4565,87.2374
3,0.18299,0.22545,0.20645,0.24245,92.8599,81.2144,61.5686,73.7697
4,0.18738,0.19636,0.20306,0.20339,83.5410,77.6834,67.6360,71.2309
...,...,...,...,...,...,...,...,...
573,0.18116,0.20147,0.23738,0.24576,72.0298,60.8287,43.0370,50.3654
574,0.19077,0.21919,0.24733,0.23882,69.3495,60.6663,52.6914,54.0085
575,0.25569,0.26058,0.25183,0.27917,68.9781,58.6687,46.1167,53.3346
576,0.17745,0.26865,0.30003,0.28667,59.8056,58.3224,40.4508,46.3041
577,0.16992,0.20050,0.20542,0.19957,97.4488,84.5106,74.9190,81.1740

In [27]:
TOPMRI_features_array = np.array(TOPMRI_features)
TOPMRI_features_array

array([[ 0.17747,  0.20996,  0.24951, ..., 80.9975 , 57.9326 , 72.1759 ],
       [ 0.1762 ,  0.23222,  0.21187, ..., 90.3336 , 67.8547 , 80.1958 ],
       [ 0.19233,  0.20855,  0.1981 , ..., 99.6353 , 72.4565 , 87.2374 ],
       ...,
       [ 0.25569,  0.26058,  0.25183, ..., 58.6687 , 46.1167 , 53.3346 ],
       [ 0.17745,  0.26865,  0.30003, ..., 58.3224 , 40.4508 , 46.3041 ],
       [ 0.16992,  0.2005 ,  0.20542, ..., 84.5106 , 74.919  , 81.174  ]])

In [28]:
# run harmonization and PUT the adjusted data into my_ad_data vaiable
my_model, my_data_adj = harmonizationLearn(TOPMRI_features_array, TOPMRI_covariates)

In [29]:
my_data_adj

array([[ 0.17799123,  0.21292426,  0.25863021, ..., 80.40156621,
        58.76713571, 71.95157533],
       [ 0.17631999,  0.23847017,  0.21314151, ..., 89.28304042,
        67.71862482, 79.55975839],
       [ 0.19677532,  0.21090314,  0.19804456, ..., 97.25412086,
        71.98241967, 85.77215988],
       ...,
       [ 0.24811787,  0.25425415,  0.24656607, ..., 55.18624034,
        43.91295781, 50.37600323],
       [ 0.17744189,  0.2598798 ,  0.28955061, ..., 54.91025754,
        36.41870877, 41.27498809],
       [ 0.17023546,  0.19998008,  0.20521044, ..., 86.21833996,
        77.16943367, 83.74278207]])

In [30]:
# turn adjusted data into dataframe with column names, then add covariates, then participant IDs
neuroharmonized_topmri = pd.DataFrame(
    my_data_adj, 
    columns = [
        'aca_b_cov', 'mca_b_cov', 'pca_b_cov', 'totalgm_b_cov',
        'aca_b_cbf', 'mca_b_cbf', 'pca_b_cbf', 'totalgm_b_cbf',]
    #'ld', 'pld', 'labelling', 'readout', 'm0']
)
neuroharmonized_topmri

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf
0,0.177991,0.212924,0.258630,0.247928,90.130796,80.401566,58.767136,71.951575
1,0.176320,0.238470,0.213142,0.238922,100.294826,89.283040,67.718625,79.559758
2,0.196775,0.210903,0.198045,0.220405,106.821333,97.254121,71.982420,85.772160
3,0.184847,0.231637,0.206382,0.249027,92.305950,80.780587,62.018760,73.486131
4,0.190124,0.196263,0.202324,0.199629,84.362774,78.019894,67.304242,71.524264
...,...,...,...,...,...,...,...,...
1102,0.180618,0.200601,0.234595,0.242574,70.403988,58.279731,39.574121,46.572342
1103,0.189104,0.216204,0.243362,0.236637,67.240891,58.127198,51.382689,51.303055
1104,0.248118,0.254254,0.246566,0.273018,66.771539,55.186240,43.912958,50.376003
1105,0.177442,0.259880,0.289551,0.278123,55.707989,54.910258,36.418709,41.274988
1106,0.170235,0.199980,0.205210,0.201662,99.185240,86.218340,77.169434,83.742782

In [31]:
neuroharmonized_topmri =pd.concat([neuroharmonized_topmri, TOPMRI_covariates.reset_index()], axis=1)
neuroharmonized_topmri

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,index,age,sex,SITE,icv
0,0.177991,0.212924,0.258630,0.247928,90.130796,80.401566,58.767136,71.951575,0,50.400000,1,0,1.394327
1,0.176320,0.238470,0.213142,0.238922,100.294826,89.283040,67.718625,79.559758,1,37.020000,1,0,1.626728
2,0.196775,0.210903,0.198045,0.220405,106.821333,97.254121,71.982420,85.772160,2,30.570000,1,0,1.407353
3,0.184847,0.231637,0.206382,0.249027,92.305950,80.780587,62.018760,73.486131,3,47.050000,1,0,1.383115
4,0.190124,0.196263,0.202324,0.199629,84.362774,78.019894,67.304242,71.524264,4,44.630000,1,0,1.428306
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,0.180618,0.200601,0.234595,0.242574,70.403988,58.279731,39.574121,46.572342,573,67.178082,1,1,1.350251
1103,0.189104,0.216204,0.243362,0.236637,67.240891,58.127198,51.382689,51.303055,574,67.794521,1,1,1.356505
1104,0.248118,0.254254,0.246566,0.273018,66.771539,55.186240,43.912958,50.376003,575,54.769863,0,1,1.646425
1105,0.177442,0.259880,0.289551,0.278123,55.707989,54.910258,36.418709,41.274988,576,66.639344,1,1,1.409838
1106,0.170235,0.199980,0.205210,0.201662,99.185240,86.218340,77.169434,83.742782,577,45.336986,1,1,1.374682

In [32]:
neuroharmonized_topmri = neuroharmonized_topmri.drop('index', axis=1)
neuroharmonized_topmri = pd.concat([neuroharmonized_topmri, TOPMRI.participant_id.reset_index()], axis=1)
neuroharmonized_topmri

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,index,participant_id
0,0.177991,0.212924,0.258630,0.247928,90.130796,80.401566,58.767136,71.951575,50.400000,1,0,1.394327,0,sub-0668_1
1,0.176320,0.238470,0.213142,0.238922,100.294826,89.283040,67.718625,79.559758,37.020000,1,0,1.626728,1,sub-0532_1
2,0.196775,0.210903,0.198045,0.220405,106.821333,97.254121,71.982420,85.772160,30.570000,1,0,1.407353,2,sub-0529_1
3,0.184847,0.231637,0.206382,0.249027,92.305950,80.780587,62.018760,73.486131,47.050000,1,0,1.383115,3,sub-0393_1
4,0.190124,0.196263,0.202324,0.199629,84.362774,78.019894,67.304242,71.524264,44.630000,1,0,1.428306,4,sub-0593_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,0.180618,0.200601,0.234595,0.242574,70.403988,58.279731,39.574121,46.572342,67.178082,1,1,1.350251,573,sub-5928501_1
1103,0.189104,0.216204,0.243362,0.236637,67.240891,58.127198,51.382689,51.303055,67.794521,1,1,1.356505,574,sub-5910502_1
1104,0.248118,0.254254,0.246566,0.273018,66.771539,55.186240,43.912958,50.376003,54.769863,0,1,1.646425,575,sub-5931002_1
1105,0.177442,0.259880,0.289551,0.278123,55.707989,54.910258,36.418709,41.274988,66.639344,1,1,1.409838,576,sub-5925701_1
1106,0.170235,0.199980,0.205210,0.201662,99.185240,86.218340,77.169434,83.742782,45.336986,1,1,1.374682,577,sub-5934201_1

In [33]:
TOPMRI_semi_features

,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20
3,sub-0393_1,0.65366,0.50449,0.22497,0.47260,0.83735,0.006571,27
4,sub-0593_1,0.66182,0.48806,0.27842,0.46336,0.80507,0.005731,35
...,...,...,...,...,...,...,...,...
573,sub-5928501_1,0.57040,0.44852,0.33133,0.42244,0.75462,0.013977,30
574,sub-5910502_1,0.56474,0.44446,0.34731,0.41632,0.74397,0.007008,32
575,sub-5931002_1,0.66914,0.56129,0.41598,0.40642,0.74734,0.015069,40
576,sub-5925701_1,0.58411,0.47607,0.34966,0.41431,0.75199,0.011519,30
577,sub-5934201_1,0.62603,0.44826,0.30040,0.45540,0.78148,0.004756,14

In [34]:
TOPMRI_semi_features

,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20
3,sub-0393_1,0.65366,0.50449,0.22497,0.47260,0.83735,0.006571,27
4,sub-0593_1,0.66182,0.48806,0.27842,0.46336,0.80507,0.005731,35
...,...,...,...,...,...,...,...,...
573,sub-5928501_1,0.57040,0.44852,0.33133,0.42244,0.75462,0.013977,30
574,sub-5910502_1,0.56474,0.44446,0.34731,0.41632,0.74397,0.007008,32
575,sub-5931002_1,0.66914,0.56129,0.41598,0.40642,0.74734,0.015069,40
576,sub-5925701_1,0.58411,0.47607,0.34966,0.41431,0.75199,0.011519,30
577,sub-5934201_1,0.62603,0.44826,0.30040,0.45540,0.78148,0.004756,14

In [35]:
neuroharmonized_topmri = neuroharmonized_topmri.drop('index', axis=1)
neuroharmonized_topmri = neuroharmonized_topmri.merge(TOPMRI_semi_features, on = 'participant_id')
neuroharmonized_topmri.head(3)

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,0.177991,0.212924,0.258630,0.247928,90.130796,80.401566,58.767136,71.951575,50.40,1,0,1.394327,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,0.176320,0.238470,0.213142,0.238922,100.294826,89.283040,67.718625,79.559758,37.02,1,0,1.626728,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,0.196775,0.210903,0.198045,0.220405,106.821333,97.254121,71.982420,85.772160,30.57,1,0,1.407353,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20

In [36]:
# create adjusted csvs
top_neuroharm_to_stroke = neuroharmonized_topmri[neuroharmonized_topmri.SITE == 0]
stroke_neuroharm_to_top = neuroharmonized_topmri[neuroharmonized_topmri.SITE == 1]

In [37]:
top_neuroharm_to_stroke.head(3)

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,0.177991,0.212924,0.258630,0.247928,90.130796,80.401566,58.767136,71.951575,50.40,1,0,1.394327,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,0.176320,0.238470,0.213142,0.238922,100.294826,89.283040,67.718625,79.559758,37.02,1,0,1.626728,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,0.196775,0.210903,0.198045,0.220405,106.821333,97.254121,71.982420,85.772160,30.57,1,0,1.407353,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20

In [38]:
# reorganize to familair pattern
column_to_move1 = stroke_neuroharm_to_top.pop("participant_id")
column_to_move2 = stroke_neuroharm_to_top.pop("age")
column_to_move3 = stroke_neuroharm_to_top.pop("sex")
tcolumn_to_move1 = top_neuroharm_to_stroke.pop("participant_id")
tcolumn_to_move2 = top_neuroharm_to_stroke.pop("age")
tcolumn_to_move3 = top_neuroharm_to_stroke.pop("sex")
stroke_neuroharm_to_top.insert(0, "participant_id", column_to_move1)
stroke_neuroharm_to_top.insert(1, "age", column_to_move2)
stroke_neuroharm_to_top.insert(2, "sex", column_to_move3)
top_neuroharm_to_stroke.insert(0, "participant_id", tcolumn_to_move1)
top_neuroharm_to_stroke.insert(1, "age", tcolumn_to_move2)
top_neuroharm_to_stroke.insert(2, "sex", tcolumn_to_move3)

In [39]:
top_neuroharm_to_stroke = top_neuroharm_to_stroke.drop('SITE', axis=1)
stroke_neuroharm_to_top = stroke_neuroharm_to_top.drop('SITE', axis=1)
stroke_neuroharm_to_top.columns

Index(['participant_id', 'age', 'sex', 'aca_b_cov', 'mca_b_cov', 'pca_b_cov',
       'totalgm_b_cov', 'aca_b_cbf', 'mca_b_cbf', 'pca_b_cbf', 'totalgm_b_cbf',
       'icv', 'gm_vol', 'wm_vol', 'csf_vol', 'gm_icvratio', 'gmwm_icvratio',
       'wmhvol_wmvol', 'wmh_count'],
      dtype='object')

In [40]:
MRI

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,DeepWM_B_CBF,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,ICV
0,sub-5917601_1,160,70.713706,1,1,0.64526,0.44079,0.45182,0.41958,0.70620,...,46.5507,87.7219,77.3645,61.7552,67.7197,1450,2025,1,1,1.537871
1,sub-5931802_1,395,47.583562,1,1,0.64172,0.49929,0.31811,0.43980,0.78199,...,29.2374,92.8927,83.1294,68.1315,74.5787,1450,2025,1,1,1.459118
2,sub-5911901_1,58,74.104110,1,1,0.56755,0.48915,0.45260,0.37604,0.70013,...,30.9324,75.6066,63.4006,60.2426,60.9976,1450,2025,1,1,1.509281
3,sub-5910201_1,30,68.843836,0,1,0.63760,0.49391,0.44339,0.40485,0.71846,...,24.7733,72.2877,63.6202,49.5712,56.4924,1450,2025,1,1,1.574904
4,sub-5928701_1,345,61.978082,1,1,0.63397,0.52613,0.47249,0.38832,0.71059,...,30.7748,109.2973,95.9550,74.7314,83.0111,1450,2025,1,1,1.632597
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,sub-5928501_1,342,67.178082,1,1,0.57040,0.44852,0.33133,0.42244,0.75462,...,24.4424,72.0298,60.8287,43.0370,50.3654,1450,2025,1,1,1.350251
574,sub-5910502_1,37,67.794521,1,1,0.56474,0.44446,0.34731,0.41632,0.74397,...,22.2190,69.3495,60.6663,52.6914,54.0085,1450,2025,1,1,1.356505
575,sub-5931002_1,381,54.769863,0,1,0.66914,0.56129,0.41598,0.40642,0.74734,...,24.0877,68.9781,58.6687,46.1167,53.3346,1450,2025,1,1,1.646425
576,sub-5925701_1,294,66.639344,1,1,0.58411,0.47607,0.34966,0.41431,0.75199,...,22.6379,59.8056,58.3224,40.4508,46.3041,1450,2025,1,1,1.409838
577,sub-5934201_1,436,45.336986,1,1,0.62603,0.44826,0.30040,0.45540,0.78148,...,24.8571,97.4488,84.5106,74.9190,81.1740,1450,2025,1,1,1.374682

In [41]:
#top_neuroharm_to_stroke
stroke_neuroharm_to_top

,participant_id,age,sex,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,icv,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
529,sub-5917601_1,70.713706,1,0.238541,0.199602,0.302835,0.262785,89.173939,79.511124,62.691656,69.077723,1.537871,0.64526,0.44079,0.45182,0.41958,0.70620,0.023490,19
530,sub-5931802_1,47.583562,1,0.168728,0.198817,0.191363,0.207392,93.810223,84.545828,69.068035,75.476600,1.459118,0.64172,0.49929,0.31811,0.43980,0.78199,0.006786,27
531,sub-5911901_1,74.104110,1,0.180779,0.221137,0.271250,0.224219,74.982215,62.043305,61.032921,60.836266,1.509281,0.56755,0.48915,0.45260,0.37604,0.70013,0.045548,42
532,sub-5910201_1,68.843836,0,0.181245,0.213306,0.228268,0.225193,71.790019,63.159995,48.916012,55.949507,1.574904,0.63760,0.49391,0.44339,0.40485,0.71846,0.027218,27
533,sub-5928701_1,61.978082,1,0.199247,0.223466,0.222612,0.250600,114.208803,102.216048,78.043470,87.699965,1.632597,0.63397,0.52613,0.47249,0.38832,0.71059,0.008703,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,sub-5928501_1,67.178082,1,0.180618,0.200601,0.234595,0.242574,70.403988,58.279731,39.574121,46.572342,1.350251,0.57040,0.44852,0.33133,0.42244,0.75462,0.013977,30
1103,sub-5910502_1,67.794521,1,0.189104,0.216204,0.243362,0.236637,67.240891,58.127198,51.382689,51.303055,1.356505,0.56474,0.44446,0.34731,0.41632,0.74397,0.007008,32
1104,sub-5931002_1,54.769863,0,0.248118,0.254254,0.246566,0.273018,66.771539,55.186240,43.912958,50.376003,1.646425,0.66914,0.56129,0.41598,0.40642,0.74734,0.015069,40
1105,sub-5925701_1,66.639344,1,0.177442,0.259880,0.289551,0.278123,55.707989,54.910258,36.418709,41.274988,1.409838,0.58411,0.47607,0.34966,0.41431,0.75199,0.011519,30
1106,sub-5934201_1,45.336986,1,0.170235,0.199980,0.205210,0.201662,99.185240,86.218340,77.169434,83.742782,1.374682,0.62603,0.44826,0.30040,0.45540,0.78148,0.004756,14

In [42]:
top_neuroharm_to_stroke.to_csv('harm_results/neurocharm/top_neuroharm_to_stroke.csv')
stroke_neuroharm_to_top.to_csv('harm_results/neurocharm/stroke_neuroharm_to_top.csv')

# Now we join top and StrokeMRI to one dataset and harmonize to other datasets individually

In [43]:
unified_TOPMRI = TOPMRI.copy(deep=True)
unified_TOPMRI = unified_TOPMRI.reset_index()
unified_TOPMRI['site'] = 0
unified_TOPMRI= unified_TOPMRI.drop('index', axis=1)
unified_TOPMRI.head(3)

,participant_id,id,age,sex,site,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,...,deepwm_b_cbf,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,ld,pld,labelling,readout,icv
0,sub-0668_1,287,50.40,1,0,0.64252,0.48470,0.26711,0.46081,0.80843,...,24.9902,90.5294,80.9975,57.9326,72.1759,1450,2025,1,1,1.394327
1,sub-0532_1,222,37.02,1,0,0.71890,0.59546,0.31236,0.44193,0.80798,...,24.2061,101.2955,90.3336,67.8547,80.1958,1450,2025,1,1,1.626728
2,sub-0529_1,220,30.57,1,0,0.66610,0.45798,0.28326,0.47330,0.79873,...,26.5891,108.6481,99.6353,72.4565,87.2374,1450,2025,1,1,1.407353

In [44]:
#SABRE = SABRE.drop('Unnamed: 0', axis=1)
#SABRE = SABRE.assign(sex = SABRE.sex.map(sex_mapping))
#SABRE['site'] = 2
SABRE.columns = SABRE.columns.str.lower()
SABRE.head(2)

,participant_id,id,age,sex,site,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,...,deepwm_b_cbf,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,ld,pld,labelling,readout,icv
0,sub-301662_1,354,79,0,1,0.53474,0.41342,0.39915,0.39689,0.70374,...,12.6230,56.7058,46.2081,36.7907,45.6094,1800,2000,1,2,1.347325
1,sub-600024_1,642,70,1,1,0.48595,0.45846,0.31526,0.38578,0.74973,...,11.0514,48.1736,42.4557,34.2886,39.0293,1800,2000,1,2,1.259656

In [45]:
SABRE['site'] = 2
SABRE.head(3)

,participant_id,id,age,sex,site,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,...,deepwm_b_cbf,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,ld,pld,labelling,readout,icv
0,sub-301662_1,354,79,0,2,0.53474,0.41342,0.39915,0.39689,0.70374,...,12.6230,56.7058,46.2081,36.7907,45.6094,1800,2000,1,2,1.347325
1,sub-600024_1,642,70,1,2,0.48595,0.45846,0.31526,0.38578,0.74973,...,11.0514,48.1736,42.4557,34.2886,39.0293,1800,2000,1,2,1.259656
2,sub-600134_1,700,62,0,2,0.63538,0.62419,0.42615,0.37692,0.74720,...,22.6623,94.2379,79.4762,70.6984,73.6202,1800,2000,1,2,1.685716

In [46]:
TOPMRIvsSABRE= pd.concat([unified_TOPMRI, SABRE])
TOPMRIvsSABRE = TOPMRIvsSABRE.reset_index()

In [47]:
TOPMRIvsSABRE.columns

Index(['index', 'participant_id', 'id', 'age', 'sex', 'site', 'gm_vol',
       'wm_vol', 'csf_vol', 'gm_icvratio', 'gmwm_icvratio', 'wmhvol_wmvol',
       'wmh_count', 'deepwm_b_cov', 'aca_b_cov', 'mca_b_cov', 'pca_b_cov',
       'totalgm_b_cov', 'deepwm_b_cbf', 'aca_b_cbf', 'mca_b_cbf', 'pca_b_cbf',
       'totalgm_b_cbf', 'ld', 'pld', 'labelling', 'readout', 'icv'],
      dtype='object')

# >>>>>>

In [48]:
TOPMRIvsSABRE_covariates = TOPMRIvsSABRE[['age', 'sex','site', 'icv']]
TOPMRIvsSABRE_covariates = TOPMRIvsSABRE_covariates.rename(columns={'site': 'SITE'})
TOPMRIvsSABRE_covariates.head(3)

     age  sex  SITE       icv
0  50.40    1     0  1.394327
1  37.02    1     0  1.626728
2  30.57    1     0  1.407353

In [49]:
TOPMRIvsSABRE_semi_features = TOPMRIvsSABRE[unharm_features]
TOPMRIvsSABRE_features = TOPMRIvsSABRE[features_to_harmonize]
TOPMRIvsSABRE_features_array = np.array(TOPMRIvsSABRE_features)

In [50]:
my_model2, my_data_adj2 = harmonizationLearn(TOPMRIvsSABRE_features_array, TOPMRIvsSABRE_covariates)

In [51]:
my_data_adj2

array([[ 0.19051798,  0.39965909,  0.60373044, ..., 75.14865652,
        54.27749265, 67.9255818 ],
       [ 0.25276396,  0.69439007,  0.43751911, ..., 84.33296304,
        64.2396718 , 75.8286158 ],
       [ 0.41983382,  0.48855539,  0.31865413, ..., 93.1713739 ,
        68.86144449, 82.59250504],
       ...,
       [ 0.30282205,  0.32845292,  0.27262535, ..., 66.42609317,
        56.22653883, 61.0614347 ],
       [ 0.26019594,  0.27631377,  0.26682914, ..., 59.52594495,
        53.59362604, 55.39020635],
       [ 0.26661833,  0.3168782 ,  0.27950279, ..., 53.56954157,
        44.17567085, 49.90664528]])

In [52]:
# turn adjusted data into dataframe with column names, then add covariates, then participant IDs
neuroharmonized_topmrivsabre = pd.DataFrame(
    my_data_adj2, 
    columns = features_to_harmonize
)
neuroharmonized_topmrivsabre =pd.concat([neuroharmonized_topmrivsabre, TOPMRIvsSABRE_covariates.reset_index()], axis=1)
neuroharmonized_topmrivsabre = neuroharmonized_topmrivsabre.drop('index', axis=1)
neuroharmonized_topmrivsabre = pd.concat([neuroharmonized_topmrivsabre, TOPMRIvsSABRE.participant_id.reset_index()], axis=1)
neuroharmonized_topmrivsabre = neuroharmonized_topmrivsabre.drop('index', axis=1)
neuroharmonized_topmrivsabre.head(3)

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id
0,0.190518,0.399659,0.603730,0.553251,84.557049,75.148657,54.277493,67.925582,50.40,1,0,1.394327,sub-0668_1
1,0.252764,0.694390,0.437519,0.519797,95.111305,84.332963,64.239672,75.828616,37.02,1,0,1.626728,sub-0532_1
2,0.419834,0.488555,0.318654,0.440499,102.085569,93.171374,68.861444,82.592505,30.57,1,0,1.407353,sub-0529_1

In [53]:
neuroharmonized_topmrivsabre = neuroharmonized_topmrivsabre.merge(TOPMRIvsSABRE_semi_features, on = 'participant_id')
neuroharmonized_topmrivsabre

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,0.190518,0.399659,0.603730,0.553251,84.557049,75.148657,54.277493,67.925582,50.40,1,0,1.394327,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,0.252764,0.694390,0.437519,0.519797,95.111305,84.332963,64.239672,75.828616,37.02,1,0,1.626728,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,0.419834,0.488555,0.318654,0.440499,102.085569,93.171374,68.861444,82.592505,30.57,1,0,1.407353,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20
3,0.256536,0.627160,0.290723,0.580003,86.818985,75.415574,57.930824,69.494724,47.05,1,0,1.383115,sub-0393_1,0.65366,0.50449,0.22497,0.47260,0.83735,0.006571,27
4,0.311024,0.241202,0.287391,0.208171,78.046215,72.141732,64.031173,67.123852,44.63,1,0,1.428306,sub-0593_1,0.66182,0.48806,0.27842,0.46336,0.80507,0.005731,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1808,0.230636,0.284773,0.212061,0.271365,59.758123,54.300202,45.337813,49.647171,66.00,1,2,1.164665,sub-236924_1,0.52085,0.43118,0.21264,0.44721,0.81742,0.004727,22
1809,0.257146,0.267358,0.243358,0.273506,67.017036,63.380770,51.642881,57.775662,72.00,1,2,1.340832,sub-263029_1,0.56209,0.45246,0.32627,0.41921,0.75666,0.002807,16
1810,0.302822,0.328453,0.272625,0.333498,71.267433,66.426093,56.226539,61.061435,73.00,0,2,1.476383,sub-61698_1,0.56293,0.50017,0.41329,0.38129,0.72007,0.019555,18
1811,0.260196,0.276314,0.266829,0.284346,66.615975,59.525945,53.593626,55.390206,65.00,1,2,1.136500,sub-600133_1,0.50214,0.39501,0.23936,0.44183,0.78939,0.006797,25
1812,0.266618,0.316878,0.279503,0.311169,65.963186,53.569542,44.175671,49.906645,70.00,1,2,1.286642,sub-501429_1,0.49555,0.49475,0.29635,0.38515,0.76967,0.001740,19

In [54]:
# reorganize to familair pattern
column_to_move1 = neuroharmonized_topmrivsabre.pop("participant_id")
column_to_move2 = neuroharmonized_topmrivsabre.pop("age")
column_to_move3 = neuroharmonized_topmrivsabre.pop("sex")
neuroharmonized_topmrivsabre.insert(0, "participant_id", column_to_move1)
neuroharmonized_topmrivsabre.insert(1, "age", column_to_move2)
neuroharmonized_topmrivsabre.insert(2, "sex", column_to_move3)

In [55]:
# create adjusted csvs
sabre_vs_topmri_only = neuroharmonized_topmrivsabre[neuroharmonized_topmrivsabre.SITE == 2]
topmri_vs_sabre_only = neuroharmonized_topmrivsabre[neuroharmonized_topmrivsabre.SITE == 0]

In [56]:
sabre_vs_topmri_only.shape

(706, 20)

In [57]:
#topmri_vs_sabre_only

In [58]:
sabre_vs_topmri_only = sabre_vs_topmri_only.drop('SITE', axis=1)
topmri_vs_sabre_only  = topmri_vs_sabre_only.drop('SITE', axis=1)
#topmri_vs_sabre_only.columns

In [59]:
sabre_vs_topmri_only.to_csv('harm_results/neurocharm/sabre_vs_topmri_only.csv') 
topmri_vs_sabre_only.to_csv('harm_results/neurocharm/topmri_vs_sabre_only.csv')

In [60]:
Insight46['Site'] = 3
Insight46.head(2)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,DeepWM_B_CBF,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,ICV
0,sub-14314420_1,280,71.072222,1,3,0.57111,0.46361,0.42824,0.39038,0.70728,...,23.2939,78.9954,76.4183,55.5895,63.4307,1800,1800,1,3,1.462959
1,sub-15705819_2,379,73.000000,0,3,0.68754,0.51580,0.60117,0.38101,0.66685,...,15.2908,73.5148,62.6658,61.9607,60.4271,1800,1800,1,3,1.804520

In [61]:
Insight46.columns = Insight46.columns.str.lower()

In [62]:
TOPMRIvsInsight46= pd.concat([unified_TOPMRI, Insight46])
TOPMRIvsInsight46 = TOPMRIvsInsight46.reset_index()

# >>>>>>

In [63]:
TOPMRIvsInsight_covariates = TOPMRIvsInsight46[['age', 'sex','site', 'icv']]
TOPMRIvsInsight_covariates = TOPMRIvsInsight_covariates .rename(columns={'site': 'SITE'})
TOPMRIvsInsight_covariates.head(3)

     age  sex  SITE       icv
0  50.40    1     0  1.394327
1  37.02    1     0  1.626728
2  30.57    1     0  1.407353

In [64]:
TOPMRIvsInsight_semi_features = TOPMRIvsInsight46[unharm_features]
TOPMRIvsInsight_features = TOPMRIvsInsight46[features_to_harmonize]
TOPMRIvsInsight_features_array = np.array(TOPMRIvsInsight_features)

In [65]:
my_model3, my_data_adj3 = harmonizationLearn(TOPMRIvsInsight_features_array, TOPMRIvsInsight_covariates)

In [66]:
my_data_adj3

array([[9.12636552e-02, 4.40526356e-01, 6.32982465e-01, ...,
        8.28584080e+01, 5.81081596e+01, 7.26949798e+01],
       [2.07805375e-01, 7.92216613e-01, 4.21547416e-01, ...,
        9.25091842e+01, 6.87779688e+01, 8.08784077e+01],
       [5.69424995e-01, 4.68222815e-01, 3.90853489e-01, ...,
        1.02375637e+02, 7.34919791e+01, 8.80917406e+01],
       ...,
       [3.36012768e-01, 3.16105183e-01, 5.24732317e-01, ...,
        7.29035053e+01, 3.53201182e+01, 5.58940081e+01],
       [2.15042628e-01, 2.63361154e-01, 2.75002219e-01, ...,
        9.95369598e+01, 7.46950175e+01, 8.57672710e+01],
       [2.50710373e-01, 3.14601855e-01, 2.85640807e-01, ...,
        8.55632173e+01, 6.91334808e+01, 7.54675439e+01]])

In [67]:
# turn adjusted data into dataframe with column names, then add covariates, then participant IDs
neuroharmonized_topmrivinsight = pd.DataFrame(
    my_data_adj3, 
    columns = features_to_harmonize
)
neuroharmonized_topmrivinsight = pd.concat([neuroharmonized_topmrivinsight, TOPMRIvsInsight_covariates.reset_index()], axis=1)
neuroharmonized_topmrivinsight = neuroharmonized_topmrivinsight.drop('index', axis=1)
neuroharmonized_topmrivinsight = pd.concat([neuroharmonized_topmrivinsight, TOPMRIvsInsight46.participant_id.reset_index()], axis=1)
neuroharmonized_topmrivinsight = neuroharmonized_topmrivinsight .merge(TOPMRIvsInsight_semi_features, on='participant_id')
neuroharmonized_topmrivinsight = neuroharmonized_topmrivinsight.drop('index', axis=1)
neuroharmonized_topmrivinsight.head(3)

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,0.091264,0.440526,0.632982,0.571274,91.391624,82.858408,58.108160,72.694980,50.40,1,0,1.394327,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,0.207805,0.792217,0.421547,0.527080,102.658546,92.509184,68.777969,80.878408,37.02,1,0,1.626728,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,0.569425,0.468223,0.390853,0.469099,110.433123,102.375637,73.491979,88.091741,30.57,1,0,1.407353,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20

In [68]:
#neuroharmonized_topmrivinsight

In [69]:
# reorganize to familair pattern
column_to_move1 = neuroharmonized_topmrivinsight.pop("participant_id")
column_to_move2 = neuroharmonized_topmrivinsight.pop("age")
column_to_move3 = neuroharmonized_topmrivinsight.pop("sex")
neuroharmonized_topmrivinsight.insert(0, "participant_id", column_to_move1)
neuroharmonized_topmrivinsight.insert(1, "age", column_to_move2)
neuroharmonized_topmrivinsight.insert(2, "sex", column_to_move3)

In [70]:
# create adjusted csvs
insight_vs_topmri_only = neuroharmonized_topmrivinsight[neuroharmonized_topmrivinsight.SITE == 3]
topmri_vs_insight_only = neuroharmonized_topmrivinsight[neuroharmonized_topmrivinsight.SITE == 0]

In [71]:
#insight_vs_topmri_only
#topmri_vs_insight_only

In [72]:
insight_vs_topmri_only  = insight_vs_topmri_only.drop('SITE', axis=1)
topmri_vs_insight_only  = topmri_vs_insight_only.drop('SITE', axis=1)

In [73]:
insight_vs_topmri_only.shape

(617, 19)

In [74]:
insight_vs_topmri_only.to_csv('harm_results/neurocharm/insight_vs_topmri_only.csv') 
topmri_vs_insight_only.to_csv('harm_results/neurocharm/topmri_vs_insight_only.csv')

In [75]:
EDIS['Site'] = 4
EDIS.head(2)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,DeepWM_B_CBF,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,ICV
0,sub-ED003_1,1,66,1,4,0.55942,0.43780,0.24159,0.45158,0.80498,...,9.2760,135.4218,142.7780,117.9492,124.4947,800,1500,2,2,1.238806
1,sub-ED005_1,2,71,0,4,0.60938,0.51911,0.28142,0.43221,0.80040,...,26.8048,191.8253,192.3582,152.7199,166.6538,800,1500,2,2,1.409916

In [76]:
EDIS.columns = EDIS.columns.str.lower()

In [77]:
TOPMRIvsEDIS = pd.concat([unified_TOPMRI, EDIS])
TOPMRIvsEDIS = TOPMRIvsEDIS.reset_index()

# >>>>>>

In [78]:
TOPMRIvsEDIS_covariates = TOPMRIvsEDIS[['age', 'sex','site','icv']]
TOPMRIvsEDIS_covariates = TOPMRIvsEDIS_covariates .rename(columns={'site': 'SITE'})
TOPMRIvsEDIS_covariates.head(3)

     age  sex  SITE       icv
0  50.40    1     0  1.394327
1  37.02    1     0  1.626728
2  30.57    1     0  1.407353

In [79]:
TOPMRIvsEDIS_semi_features = TOPMRIvsEDIS[unharm_features]
TOPMRIvsEDIS_features = TOPMRIvsEDIS[features_to_harmonize]
TOPMRIvsEDIS_features_array = np.array(TOPMRIvsEDIS_features)

In [80]:
my_model4, my_data_adj4 = harmonizationLearn(TOPMRIvsEDIS_features_array, TOPMRIvsEDIS_covariates)

In [81]:
my_data_adj4

array([[  0.23201201,   0.27796562,   0.5320756 , ...,  85.16543711,
         59.70966416,  75.39137743],
       [  0.2740573 ,   0.48944808,   0.38904471, ...,  94.68662316,
         69.99014738,  83.55557357],
       [  0.33504208,   0.2781998 ,   0.30926033, ..., 104.56051864,
         74.72930591,  90.87510376],
       ...,
       [  0.38052285,   0.3649758 ,   0.39791296, ...,  57.77149969,
         49.69237892,  46.62196999],
       [  0.3656311 ,   0.43012074,   0.50075053, ...,  78.72816433,
         61.68197358,  68.17036018],
       [  0.24725383,   0.25065923,   0.28645541, ...,  77.34484659,
         67.02446603,  72.78319305]])

In [82]:
# turn adjusted data into dataframe with column names, then add covariates, then participant IDs
neuroharmonized_topmrivedis = pd.DataFrame(
    my_data_adj4, 
    columns = features_to_harmonize
)
neuroharmonized_topmrivedis = pd.concat([neuroharmonized_topmrivedis, TOPMRIvsEDIS_covariates.reset_index()], axis=1)
neuroharmonized_topmrivedis = neuroharmonized_topmrivedis.drop('index', axis=1)
neuroharmonized_topmrivedis = pd.concat([neuroharmonized_topmrivedis, TOPMRIvsEDIS.participant_id.reset_index()], axis=1)
neuroharmonized_topmrivedis = neuroharmonized_topmrivedis.drop('index', axis=1)
neuroharmonized_topmrivedis = neuroharmonized_topmrivedis.merge(TOPMRIvsEDIS_semi_features, on ='participant_id')
neuroharmonized_topmrivedis.head(3)

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,0.232012,0.277966,0.532076,0.431030,92.840001,85.165437,59.709664,75.391377,50.40,1,0,1.394327,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,0.274057,0.489448,0.389045,0.439841,103.910478,94.686623,69.990147,83.555574,37.02,1,0,1.626728,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,0.335042,0.278200,0.309260,0.322513,111.702704,104.560519,74.729306,90.875104,30.57,1,0,1.407353,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20

In [83]:
# reorganize to familair pattern
column_to_move1 = neuroharmonized_topmrivedis.pop("participant_id")
column_to_move2 = neuroharmonized_topmrivedis.pop("age")
column_to_move3 = neuroharmonized_topmrivedis.pop("sex")
neuroharmonized_topmrivedis.insert(0, "participant_id", column_to_move1)
neuroharmonized_topmrivedis.insert(1, "age", column_to_move2)
neuroharmonized_topmrivedis.insert(2, "sex", column_to_move3)

In [84]:
# create adjusted csvs
edis_vs_topmri_only = neuroharmonized_topmrivedis[neuroharmonized_topmrivedis.SITE == 4]
topmri_vs_edis_only = neuroharmonized_topmrivedis[neuroharmonized_topmrivedis.SITE == 0]

In [85]:
#edis_vs_topmri_only
topmri_vs_edis_only.shape

(1107, 20)

In [86]:
edis_vs_topmri_only  = edis_vs_topmri_only.drop('SITE', axis=1)
topmri_vs_edis_only  = topmri_vs_edis_only.drop('SITE', axis=1)

In [87]:
edis_vs_topmri_only.to_csv('harm_results/neurocharm/edis_vs_topmri_only.csv') 
topmri_vs_edis_only.to_csv('harm_results/neurocharm/topmri_vs_edis_only.csv')

In [88]:
HELIUS['Site'] = 5
HELIUS.head(2)

,participant_id,ID,Age,Sex,Site,GM_vol,WM_vol,CSF_vol,GM_ICVRatio,GMWM_ICVRatio,...,DeepWM_B_CBF,ACA_B_CBF,MCA_B_CBF,PCA_B_CBF,TotalGM_B_CBF,LD,PLD,Labelling,Readout,ICV
0,sub-231538_1,513,66,1,5,0.51427,0.41449,0.32213,0.41112,0.74248,...,22.7753,87.9563,82.1197,59.8673,71.0324,1800,1800,1,2,1.250900
1,sub-162765_1,353,56,1,5,0.48033,0.45722,0.31757,0.38270,0.74698,...,12.2412,76.0845,67.1553,54.9936,60.5798,1800,1800,1,2,1.255108

In [89]:
HELIUS.columns = HELIUS.columns.str.lower()

In [90]:
TOPMRIvsHELIUS = pd.concat([unified_TOPMRI, HELIUS])
TOPMRIvsHELIUS = TOPMRIvsHELIUS.reset_index()

# >>>>>>

In [91]:
TOPMRIvsHELIUS_covariates = TOPMRIvsHELIUS[['age', 'sex','site', 'icv']]
TOPMRIvsHELIUS_covariates = TOPMRIvsHELIUS_covariates .rename(columns={'site': 'SITE'})
TOPMRIvsHELIUS_covariates.head(3)

     age  sex  SITE       icv
0  50.40    1     0  1.394327
1  37.02    1     0  1.626728
2  30.57    1     0  1.407353

In [92]:
TOPMRIvsHELIUS_semi_features = TOPMRIvsHELIUS[unharm_features]
TOPMRIvsHELIUS_features = TOPMRIvsHELIUS[features_to_harmonize]
TOPMRIvsHELIUS_features_array = np.array(TOPMRIvsHELIUS_features)

In [93]:
my_model5, my_data_adj5 = harmonizationLearn(TOPMRIvsHELIUS_features_array, TOPMRIvsHELIUS_covariates)

In [94]:
my_data_adj5

array([[ 0.22563229,  0.26418169,  0.33996294, ..., 80.38979746,
        57.72109711, 71.69820945],
       [ 0.22606472,  0.30383529,  0.28021933, ..., 89.58968539,
        67.28661197, 79.56249616],
       [ 0.24898876,  0.26416257,  0.26435045, ..., 98.58163364,
        71.76219892, 86.34918208],
       ...,
       [ 0.20989276,  0.22704174,  0.24247125, ..., 81.54595967,
        66.19011233, 74.33094755],
       [ 0.23773616,  0.26482926,  0.28430919, ..., 57.14862361,
        45.04537283, 52.46029381],
       [ 0.23701089,  0.25009285,  0.28471706, ..., 62.27520221,
        47.80677804, 56.68400432]])

In [95]:
# turn adjusted data into dataframe with column names, then add covariates, then participant IDs
neuroharmonized_topmrivhelius = pd.DataFrame(
    my_data_adj5, 
    columns = features_to_harmonize
)
neuroharmonized_topmrivhelius = pd.concat([neuroharmonized_topmrivhelius, TOPMRIvsHELIUS_covariates.reset_index()], axis=1)
neuroharmonized_topmrivhelius = neuroharmonized_topmrivhelius.drop('index', axis=1)
neuroharmonized_topmrivhelius = pd.concat([neuroharmonized_topmrivhelius, TOPMRIvsHELIUS.participant_id.reset_index()], axis=1)
neuroharmonized_topmrivhelius = neuroharmonized_topmrivhelius.drop('index', axis=1)
neuroharmonized_topmrivhelius = neuroharmonized_topmrivhelius.merge(TOPMRIvsHELIUS_semi_features , on='participant_id')
neuroharmonized_topmrivhelius.head(3)

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,0.225632,0.264182,0.339963,0.307986,90.226470,80.389797,57.721097,71.698209,50.40,1,0,1.394327,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,0.226065,0.303835,0.280219,0.298744,100.884158,89.589685,67.286612,79.562496,37.02,1,0,1.626728,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,0.248989,0.264163,0.264350,0.277687,108.079946,98.581634,71.762199,86.349182,30.57,1,0,1.407353,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20

In [96]:
# reorganize to familair pattern
column_to_move1 = neuroharmonized_topmrivhelius.pop("participant_id")
column_to_move2 = neuroharmonized_topmrivhelius.pop("age")
column_to_move3 = neuroharmonized_topmrivhelius.pop("sex")
neuroharmonized_topmrivhelius.insert(0, "participant_id", column_to_move1)
neuroharmonized_topmrivhelius.insert(1, "age", column_to_move2)
neuroharmonized_topmrivhelius.insert(2, "sex", column_to_move3)

In [97]:
#neuroharmonized_topmrivhelius

In [98]:
# create adjusted csvs
helius_vs_topmri_only = neuroharmonized_topmrivhelius[neuroharmonized_topmrivhelius.SITE == 5]
topmri_vs_helius_only = neuroharmonized_topmrivhelius[neuroharmonized_topmrivhelius.SITE == 0]

In [99]:
helius_vs_topmri_only  = helius_vs_topmri_only.drop('SITE', axis=1)
topmri_vs_helius_only  = topmri_vs_helius_only.drop('SITE', axis=1)

In [100]:
helius_vs_topmri_only.shape

(556, 19)

In [101]:
helius_vs_topmri_only.to_csv('harm_results/neurocharm/helius_vs_topmri_only.csv') 
topmri_vs_helius_only.to_csv('harm_results/neurocharm/topmri_vs_helius_only.csv')

# Now we will do five way harmonization- TOPMRI vs. SAbre vs. Insigth46 vs. EDIS vs. others

In [102]:
TOPMRIvsSABRvsInisghvsEDISvsHELIUS = pd.concat([unified_TOPMRI, SABRE, Insight46, EDIS, HELIUS])
TOPMRIvsSABRvsInisghvsEDISvsHELIUS = TOPMRIvsSABRvsInisghvsEDISvsHELIUS.reset_index()

# >>>>>>

In [103]:
TOPMRIvsSABRvsInisghvsEDISvsHELIUS_covariates = TOPMRIvsSABRvsInisghvsEDISvsHELIUS[['age', 'sex','site', 'icv']]
TOPMRIvsSABRvsInisghvsEDISvsHELIUS_covariates = TOPMRIvsSABRvsInisghvsEDISvsHELIUS_covariates.rename(columns={'site': 'SITE'})
TOPMRIvsSABRvsInisghvsEDISvsHELIUS_covariates.head(3)

     age  sex  SITE       icv
0  50.40    1     0  1.394327
1  37.02    1     0  1.626728
2  30.57    1     0  1.407353

In [104]:
TOPMRIvsSABRvsInisghvsEDISvsHELIUS.columns

Index(['index', 'participant_id', 'id', 'age', 'sex', 'site', 'gm_vol',
       'wm_vol', 'csf_vol', 'gm_icvratio', 'gmwm_icvratio', 'wmhvol_wmvol',
       'wmh_count', 'deepwm_b_cov', 'aca_b_cov', 'mca_b_cov', 'pca_b_cov',
       'totalgm_b_cov', 'deepwm_b_cbf', 'aca_b_cbf', 'mca_b_cbf', 'pca_b_cbf',
       'totalgm_b_cbf', 'ld', 'pld', 'labelling', 'readout', 'icv'],
      dtype='object')

In [105]:
TOPMRIvsSABRvsInisghvsEDISvsHELIUS_semi_features = TOPMRIvsSABRvsInisghvsEDISvsHELIUS[unharm_features]
TOPMRIvsSABRvsInisghvsEDISvsHELIUS_features = TOPMRIvsSABRvsInisghvsEDISvsHELIUS[features_to_harmonize]
TOPMRIvsSABRvsInisghvsEDISvsHELIUS_features_array = np.array(TOPMRIvsSABRvsInisghvsEDISvsHELIUS_features)

In [106]:
my_modelA, my_data_adjA = harmonizationLearn(TOPMRIvsSABRvsInisghvsEDISvsHELIUS_features_array, TOPMRIvsSABRvsInisghvsEDISvsHELIUS_covariates)

In [107]:
my_data_adjA

array([[ 1.59644248e-01,  5.05420026e-01,  7.57576368e-01, ...,
         7.99319121e+01,  5.61544621e+01,  7.07707026e+01],
       [ 4.12319297e-01,  9.35047999e-01,  5.90913838e-01, ...,
         8.94290834e+01,  6.65631525e+01,  7.88205212e+01],
       [ 6.43175566e-01,  5.97691980e-01,  5.10341256e-01, ...,
         9.90624542e+01,  7.13274518e+01,  8.59047840e+01],
       ...,
       [-1.35645509e-01,  5.82591615e-02,  2.80705147e-01, ...,
         8.13774899e+01,  6.62139057e+01,  7.40627792e+01],
       [ 1.09093026e-01,  1.19202602e-01,  3.39716530e-01, ...,
         5.57137414e+01,  4.34077997e+01,  5.12949473e+01],
       [ 2.77254328e-01,  2.92918071e-01,  5.10150164e-01, ...,
         6.04284862e+01,  4.53794997e+01,  5.51448039e+01]])

In [108]:
# turn adjusted data into dataframe with column names, then add covariates, then participant IDs
neuroharmonized_A= pd.DataFrame(
    my_data_adjA, 
    columns = features_to_harmonize
)
neuroharmonized_A =pd.concat([neuroharmonized_A, TOPMRIvsSABRvsInisghvsEDISvsHELIUS_covariates .reset_index()], axis=1)
neuroharmonized_A = neuroharmonized_A.drop('index', axis=1)
neuroharmonized_A = pd.concat([neuroharmonized_A, TOPMRIvsSABRvsInisghvsEDISvsHELIUS.participant_id.reset_index()], axis=1)
neuroharmonized_A = neuroharmonized_A.drop('index', axis=1)
neuroharmonized_A = neuroharmonized_A.merge(TOPMRIvsSABRvsInisghvsEDISvsHELIUS_semi_features, on='participant_id') 
neuroharmonized_A.head(3)

,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,age,sex,SITE,icv,participant_id,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
0,0.159644,0.505420,0.757576,0.676948,88.194480,79.931912,56.154462,70.770703,50.40,1,0,1.394327,sub-0668_1,0.64252,0.48470,0.26711,0.46081,0.80843,0.004506,18
1,0.412319,0.935048,0.590914,0.683958,99.234535,89.429083,66.563152,78.820521,37.02,1,0,1.626728,sub-0532_1,0.71890,0.59546,0.31236,0.44193,0.80798,0.002501,24
2,0.643176,0.597692,0.510341,0.578081,106.939238,99.062454,71.327452,85.904784,30.57,1,0,1.407353,sub-0529_1,0.66610,0.45798,0.28326,0.47330,0.79873,0.005144,20

In [109]:
# reorganize to familair pattern
column_to_move1 = neuroharmonized_A.pop("participant_id")
column_to_move2 = neuroharmonized_A.pop("age")
column_to_move3 = neuroharmonized_A.pop("sex")
neuroharmonized_A.insert(0, "participant_id", column_to_move1)
neuroharmonized_A.insert(1, "age", column_to_move2)
neuroharmonized_A.insert(2, "sex", column_to_move3)

In [110]:
# create adjusted csvs
insight_vs_topmri_5way= neuroharmonized_A[neuroharmonized_A.SITE == 3]
sabre_vs_topmri_5way = neuroharmonized_A[neuroharmonized_A.SITE == 2]
topmri_vs_sabre_5way = neuroharmonized_A[neuroharmonized_A.SITE == 0] 
edis_vs_topmri_5way= neuroharmonized_A[neuroharmonized_A.SITE == 4]
helius_vs_topmri_5way = neuroharmonized_A[neuroharmonized_A.SITE == 5]

In [111]:
insight_vs_topmri_5way = insight_vs_topmri_5way.drop('SITE', axis=1)
sabre_vs_topmri_5way = sabre_vs_topmri_5way.drop('SITE', axis=1) 
topmri_vs_sabre_5way = topmri_vs_sabre_5way.drop('SITE', axis=1)  

edis_vs_topmri_5way = edis_vs_topmri_5way.drop('SITE', axis=1) 
helius_vs_topmri_5way = helius_vs_topmri_5way.drop('SITE', axis=1)

In [112]:
helius_vs_topmri_5way

,participant_id,age,sex,aca_b_cov,mca_b_cov,pca_b_cov,totalgm_b_cov,aca_b_cbf,mca_b_cbf,pca_b_cbf,totalgm_b_cbf,icv,gm_vol,wm_vol,csf_vol,gm_icvratio,gmwm_icvratio,wmhvol_wmvol,wmh_count
2776,sub-231538_1,66.0,1,0.894375,0.483538,0.257293,0.560987,87.892377,84.373986,60.491894,72.442506,1.250900,0.51427,0.41449,0.32213,0.41112,0.74248,0.004905,13
2777,sub-162765_1,56.0,1,0.592097,0.512080,0.384404,0.490873,74.126636,66.096187,53.769620,59.292687,1.255108,0.48033,0.45722,0.31757,0.38270,0.74698,0.004313,17
2778,sub-101214_1,73.0,0,0.132617,0.381317,0.532487,0.389218,77.471407,64.289411,56.276779,61.783017,1.505506,0.52360,0.43520,0.54672,0.34779,0.63686,0.023320,35
2779,sub-162593_1,47.0,0,1.085740,1.066223,1.024573,0.951546,89.613076,71.328866,67.268875,71.717166,1.308394,0.52935,0.45694,0.32211,0.40458,0.75381,0.003256,28
2780,sub-103633_1,69.0,1,-0.258171,0.174194,0.212030,0.109753,96.820084,82.343977,66.423246,74.205524,1.485955,0.57028,0.50081,0.41488,0.38378,0.72080,0.027000,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,sub-211342_1,57.0,1,0.517345,0.703647,0.475228,0.500548,47.787209,38.856519,30.235672,37.354726,1.266043,0.57096,0.43418,0.26090,0.45098,0.79392,0.002819,16
3328,sub-232697_1,55.0,1,-0.036335,0.377502,0.434503,0.422350,97.785749,87.082099,71.197824,79.308624,1.089372,0.47343,0.39916,0.21679,0.43459,0.80100,0.003998,20
3329,sub-205033_1,61.0,1,-0.135646,0.058259,0.280705,0.126259,85.744257,81.377490,66.213906,74.062779,1.269540,0.49507,0.38732,0.38714,0.38996,0.69505,0.003519,12
3330,sub-101158_1,68.0,0,0.109093,0.119203,0.339717,0.164482,61.233462,55.713741,43.407800,51.294947,1.583204,0.63306,0.52261,0.42754,0.39986,0.72995,0.007889,20
3331,sub-138548_1,58.0,1,0.277254,0.292918,0.510150,0.542215,66.993288,60.428486,45.379500,55.144804,1.236520,0.52170,0.43188,0.28295,0.42191,0.77117,0.006041,23

In [113]:
insight_vs_topmri_5way.to_csv('harm_results/neurocharm/insight_vs_topmri_5way.csv')
helius_vs_topmri_5way.to_csv('harm_results/neurocharm/helius_vs_topmri_5way.csv')
sabre_vs_topmri_5way.to_csv('harm_results/neurocharm/sabre_vs_topmri_5way.csv')
topmri_vs_sabre_5way.to_csv('harm_results/neurocharm/topmri_vs_sabre_5way.csv')
edis_vs_topmri_5way.to_csv('harm_results/neurocharm/edis_vs_topmri_5way.csv')

In [114]:
# end of notebook!

In [115]:
#insight_vs_topmri_5way